import React, { useMemo, useState } from "react";
import { buildRoleSensitiveVisual } from "./roleSensitiveVisualData.js";
import BlueprintTracePanel from "../blueprint/BlueprintTracePanel.jsx";
import { createBlueprintTrace } from "../blueprint/blueprintTraceData.js";

export default function RoleSensitiveVisual({ result, familyId, roleTitle, onBack, onEvidenceSelect }) {
  const data = useMemo(() => buildRoleSensitiveVisual(result, familyId), [result, familyId]);
  const [selectedId, setSelectedId] = useState(null);
  const selected = data.items.find((item) => item.id === selectedId) || null;
  const byId = new Map(data.items.map((item) => [item.id, item]));
  const trace = createBlueprintTrace({ id: `trace:visual:${familyId}`, requirement: "BLP-025", component: data.contract?.label || "Role-sensitive visual", sourceIds: data.evidenceIds || [], status: data.status === "available" ? "AVAILABLE" : "WITHHELD", rule: data.status === "available" ? `Rendered because a ${data.contract.version} supplied-data payload contains source-linked ${data.contract.itemName} items.` : data.boundary, knownGap: data.excluded.length ? `${data.excluded.length} malformed entries withheld` : null });
  return (
    <section className={`rsv-root ${data.contract?.layout || "unknown"}`} data-testid="role-sensitive-visual" data-family={familyId} data-status={data.status} aria-label={data.contract?.label || "Unavailable visual"}>
      <style>{`.rsv-root{height:100%;min-height:0;display:grid;grid-template-rows:auto auto minmax(0,1fr) auto;background:#f5f7fa;color:#1e293b}.rsv-head,.rsv-contract,.rsv-footer{display:flex;justify-content:space-between;align-items:center;gap:10px;padding:10px 14px;background:#fff;border-bottom:1px solid #dbe3ec}.rsv-title{font:800 clamp(19px,2vw,28px)/1.1 Georgia,serif}.rsv-meta,.rsv-boundary{font-size:9px;color:#64748b}.rsv-head button,.rsv-evidence button{min-height:44px;border:1px solid #cbd5e1;border-radius:8px;background:#fff;padding:0 10px;font-size:9px;font-weight:900}.rsv-status{border:1px solid #1a56db;border-radius:999px;padding:3px 8px;color:#1a56db;font-size:8px;font-weight:900}.rsv-status.withheld{border-style:dashed;border-color:#b7791f;color:#92400e}.rsv-body{min-height:0;overflow:auto;padding:16px}.rsv-items{display:grid;grid-template-columns:repeat(auto-fit,minmax(180px,1fr));gap:9px;max-width:980px;margin:0 auto}.rsv-root.funnel .rsv-items,.rsv-root.trace .rsv-items{grid-template-columns:1fr;max-width:720px}.rsv-root.portfolio .rsv-items{grid-template-columns:repeat(auto-fit,minmax(230px,1fr))}.rsv-item{min-height:92px;border:1px solid #dbe3ec;border-left:4px solid #1a56db;border-radius:10px;background:#fff;padding:11px;text-align:left}.rsv-item.active{box-shadow:0 0 0 3px rgba(26,86,219,.12)}.rsv-item b{display:block;font-size:11px}.rsv-item span{display:block;margin-top:4px;color:#64748b;font-size:9px;line-height:1.4}.rsv-detail,.rsv-links,.rsv-empty{max-width:980px;margin:12px auto 0;border:1px solid #dbe3ec;border-radius:10px;background:#fff;padding:12px}.rsv-empty{border-style:dashed;background:#fffbeb;color:#92400e}.rsv-evidence{display:flex;flex-wrap:wrap;gap:5px;margin-top:7px}.rsv-link{padding:6px 0;border-top:1px solid #e7edf4;font-size:9px}.rsv-footer{border-top:1px solid #dbe3ec;border-bottom:0}@media(max-width:600px){.rsv-head,.rsv-contract,.rsv-footer{align-items:stretch;flex-direction:column}.rsv-head button{width:100%}.rsv-items{grid-template-columns:1fr}.rsv-body{padding:12px}}`}</style>
      <header className="rsv-head"><div><div className="om-eyebrow">Role-sensitive visual · contract {data.contract?.version || "unavailable"}</div><div className="rsv-title">{data.contract?.label || "Unavailable visual"}</div><div className="rsv-meta">{roleTitle} · {data.contract?.question}</div></div><button data-testid="role-sensitive-visual-back" type="button" onClick={onBack}>← Five-graph universe</button></header>
      <div className="rsv-contract"><div className="rsv-boundary"><b>Evidence boundary:</b> {data.boundary}</div><span className={`rsv-status ${data.status}`}>{data.status === "available" ? "SUPPLIED" : data.status.toUpperCase()}</span></div>
      <div style={{ padding: "0 14px", background: "#fff" }}><BlueprintTracePanel traces={[trace]} label={`${data.contract?.label || "Visual"} blueprint trace`} /></div>
      <div className="rsv-body">{data.items.length ? <><div className="rsv-items">{data.items.map((item) => <button type="button" className={`rsv-item ${selectedId === item.id ? "active" : ""}`} data-testid={`role-visual-item-${item.id}`} aria-expanded={selectedId === item.id} key={item.id} onClick={() => setSelectedId(selectedId === item.id ? null : item.id)}><b>{item.order}. {item.label}</b><span>{item.description || `${data.contract.itemName} supplied`}</span><span>{item.evidenceIds.length} source link{item.evidenceIds.length === 1 ? "" : "s"}</span></button>)}</div>{selected && <section className="rsv-detail" data-testid="role-sensitive-visual-detail" aria-live="polite"><b>{selected.label}</b><p className="rsv-meta">{selected.description || "No additional description supplied."}</p><div className="rsv-evidence">{selected.evidenceIds.map((id) => <button type="button" key={id} onClick={() => onEvidenceSelect?.(id)}>{id}</button>)}</div></section>}<section className="rsv-links"><b>Supplied relationships</b>{data.links.length ? data.links.map((link) => <div className="rsv-link" key={link.id}>{byId.get(link.from)?.label} → {link.label} → {byId.get(link.to)?.label} · {link.evidenceIds.join(" · ")}</div>) : <p className="rsv-meta">No relationships supplied. The visual does not invent them.</p>}</section></> : <div className="rsv-empty" data-testid="role-sensitive-visual-withheld">WITHHELD · {data.boundary}</div>}</div>
      <footer className="rsv-footer"><span className="rsv-meta">{data.evidenceIds?.length || 0} source identifiers · {data.excluded.length} malformed entries withheld</span><span className="rsv-meta">AI-assisted · human decides</span></footer>
    </section>
  );
}
